version: "2"

services:
  jpo_postgres:
    image: "postgres:9.6-alpine"
    hostname: jpo_postgres
    ports:
      - "5432:5432"

  jpo_mysql:
    image: "mysql:5.7"
    hostname: jpo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"

  jpo_oracle:
    image: "wnameless/oracle-xe-11g"
    hostname: jpo_oracle
    ports:
      - "49160:22"
      - "49161:1521"

