/*******************************************************************************
 * Copyright 2013 Francesco Cina'
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package com.jporm.test.domain.section02;

import com.jporm.annotation.Column;
import com.jporm.annotation.Generator;
import com.jporm.annotation.Id;
import com.jporm.annotation.Table;
import com.jporm.annotation.generator.GeneratorType;

/**
 * 
 * @author Francesco Cina
 *
 * 08/giu/2011
 */
@Table(tableName="BLOBCLOB")
public class Blobclob_String {

	@Column(name="BLOB_FIELD")
	private byte[] blobField;
	@Column(name="CLOB_FIELD")
	private String clobField;

	@Id
	@Generator(generatorType = GeneratorType.SEQUENCE_FALLBACK_AUTOGENERATED, name = "SEQ_BLOBCLOB")
	private long id = -1l;

	public long getId() {
		return id;
	}
	public void setId(final long id) {
		this.id = id;
	}
	public byte[] getBlobField() {
		return blobField;
	}
	public void setBlobField(final byte[] blob) {
		this.blobField = blob;
	}
	public String getClobField() {
		return clobField;
	}
	public void setClobField(final String clob) {
		this.clobField = clob;
	}



}
