/*******************************************************************************
 * Copyright 2013 Francesco Cina'
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package com.jporm.sql.dsl.query;

import java.util.List;

import com.jporm.sql.dsl.dialect.DBProfile;
import com.jporm.sql.dsl.query.processor.PropertiesProcessor;

/**
 *
 * @author Francesco Cina
 *
 *         23/giu/2011
 */
public interface SqlSubElement {

    /**
     * Append to the list all the values of the expression's elements
     *
     * @return
     */
    void sqlElementValues(List<Object> values);

    /**
     * @return
     */
    String sqlElementQuery(DBProfile profile, PropertiesProcessor propertiesProcessor);

    /**
     * Append to the string buffer the sql query generated by this IQuery Object
     *
     * @param queryBuilder
     */
    void sqlElementQuery(StringBuilder queryBuilder, DBProfile profile, PropertiesProcessor propertiesProcessor);

}