/*******************************************************************************
 * Copyright 2013 Francesco Cina'
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package com.jporm.commons.core.query.find;

import com.jporm.commons.core.query.Query;
import com.jporm.sql.dsl.query.select.SelectCommon;
import com.jporm.sql.dsl.query.where.SelectCommonSupplier;

/**
 *
 * @author Francesco Cina
 *
 *         07/lug/2011
 */
public interface CommonFindQueryRoot extends Query, SelectCommonSupplier {
    // do nothing

    /**
     * Return the sql query generated by this IQuery Object
     *
     * @return
     */
    @Override
    SelectCommon sql();
}
