/*******************************************************************************
 * Copyright 2016 Francesco Cina'
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package com.jporm.sql.query.insert.values;

import com.jporm.sql.dialect.SqlFunctionsRender;

public interface Generator {

    /**
     * Return a {@link Generator} that uses a sequence to generate the field value
     * @param sequenceName
     * @return
     */
    public static Generator sequence(String sequenceName) {
        return new SequenceGenerator(sequenceName);
    }

    /**
     * Return a {@link Generator} that uses an in memory generated UUID
     * @return
     */
    public static Generator uuid() {
        return new UUIDGenerator();
    }

    /**
     * Return a {@link Generator} that uses the database specific auto generated feature if any
     * @return
     */
    public static Generator auto() {
        return new AutoGeneratedGenerator();
    }

    /**
     * Return a NoOps {@link Generator}
     * @return
     */
    public static Generator noOps() {
        return new NoOpsGenerator();
    }


    boolean isRequiredColumnNameInInsertQuery();
    boolean replaceQuestionMark();
    boolean hasValue();

    Object getValue();

    void questionMarkReplacement(StringBuilder queryBuilder, SqlFunctionsRender functionsRender);

}
